In [40]:
import finlab
from finlab import data
import pandas as pd
import datetime as dt
import numpy as np
import math
from dotenv import load_dotenv
import os
import time
def config():
    load_dotenv()


    
config()

finlab.login(str(os.getenv('FINLAB_API')))

輸入成功!

In [2]:
# 營業利益 "data.get('fundamental_features:營業利益')""	float	
# EBITDA	"data.get('fundamental_features:EBITDA')"	float	
# 營運現金流	"data.get('fundamental_features:營運現金流')"	float	
# 歸屬母公司淨利	"data.get('fundamental_features:歸屬母公司淨利')	float	
# 折舊	data.get('fundamental_features:折舊')	float	
# 流動資產	data.get('fundamental_features:流動資產')	float	
# 流動負債	data.get('fundamental_features:流動負債')	float	
# 取得不動產廠房及設備	data.get('fundamental_features:取得不動產廠房及設備')
# 經常稅後淨利	data.get('fundamental_features:經常稅後淨利')	float	
# ROA稅後息前	data.get('fundamental_features:ROA稅後息前')	float	
# ROA綜合損益	data.get('fundamental_features:ROA綜合損益')	float	
# ROE稅後	data.get('fundamental_features:ROE稅後')	float	
# ROE綜合損益	data.get('fundamental_features:ROE綜合損益')	float	
# 稅前息前折舊前淨利率	data.get('fundamental_features:稅前息前折舊前淨利率')	float	
# 營業毛利率	data.get('fundamental_features:營業毛利率')	float	
# 營業利益率	data.get('fundamental_features:營業利益率')	float
# 稅前淨利率	data.get('fundamental_features:稅前淨利率')	float	
# 稅後淨利率	data.get('fundamental_features:稅後淨利率')	float	
# 業外收支營收率	data.get('fundamental_features:業外收支營收率')	float	
# 貝里比率	data.get('fundamental_features:貝里比率')	float	
# 營業費用率	data.get('fundamental_features:營業費用率')	float	
# 推銷費用率	data.get('fundamental_features:推銷費用率')	float	
# 管理費用率	data.get('fundamental_features:管理費用率')	float	
# 研究發展費用率	data.get('fundamental_features:研究發展費用率')	float	
# 現金流量比率	data.get('fundamental_features:現金流量比率')	float	
# 稅率	data.get('fundamental_features:稅率')	float	
# 每股營業額	data.get('fundamental_features:每股營業額')	float	
# 每股營業利益	data.get('fundamental_features:每股營業利益')	float	
# 每股現金流量	data.get('fundamental_features:每股現金流量')	float	
# 每股稅前淨利	data.get('fundamental_features:每股稅前淨利')	float	
# 每股綜合損益	data.get('fundamental_features:每股綜合損益')	float	
# 每股稅後淨利	data.get('fundamental_features:每股稅後淨利')	float
# 總負債除總淨值	data.get('fundamental_features:總負債除總淨值')	float	
# 負債比率	data.get('fundamental_features:負債比率')	float	
# 淨值除資產	data.get('fundamental_features:淨值除資產')	float	
# 營收成長率	data.get('fundamental_features:營收成長率')	float	
# 營業毛利成長率	data.get('fundamental_features:營業毛利成長率')	float	
# 營業利益成長率	data.get('fundamental_features:營業利益成長率')	float	
# 稅前淨利成長率	data.get('fundamental_features:稅前淨利成長率')	float	
# 稅後淨利成長率	data.get('fundamental_features:稅後淨利成長率')	float	
# 資產總額成長率	data.get('fundamental_features:資產總額成長率')	float	
# 淨值成長率	data.get('fundamental_features:淨值成長率')	float	
# 流動比率	data.get('fundamental_features:流動比率')	float	
# 速動比率	data.get('fundamental_features:速動比率')	float	
# 利息支出率	data.get('fundamental_features:利息支出率')	float	
# 營運資金	data.get('fundamental_features:營運資金')	float	
# 總資產週轉次數	data.get('fundamental_features:總資產週轉次數')	float	
# 應收帳款週轉率	data.get('fundamental_features:應收帳款週轉率')	float

In [45]:
roe = data.get('fundamental_features:ROE稅後').deadline()
Receivables_turnover_ratio = data.get('fundamental_features:應收帳款週轉率').deadline()
profit = data.get('fundamental_features:營業利益').deadline()
profit.dropna(axis=1, how='all').stack(dropna=False)
price_data = data.get('etl:adj_close')

In [105]:
Receivables_turnover_ratio[Receivables_turnover_ratio.columns.isin(price_data_stock_columns)]

ValueError: Item wrong length 1781 instead of 55.

In [18]:
Receivables_turnover_ratio.stack()

date     symbol
2013-Q2  1101       1.499238
         1102       1.170351
         1103       1.895246
         1104       1.279083
         1108       0.525799
                     ...
2020-Q3  9951       1.376963
         9955      50.620248
         9958       2.555440
         9960       8.651311
         9962       6.943470
Length: 47140, dtype: float64

In [7]:
cleaned_roe = roe.dropna(axis=1)

In [27]:
cleaned_roe.reset_index()
# turn it into a multi index dataframe
stack_roe = cleaned_roe.stack(dropna=False)
stack_Receivables_turnover_ratio = Receivables_turnover_ratio.stack(dropna=False)
a = pd.concat([cleaned_roe, Receivables_turnover_ratio], axis=1)
a.stack()

date     symbol
2013-Q1  1101       1.375582
         1102       1.315619
         1103       0.363729
         1104       1.335893
         1108       1.491161
                     ...
2020-Q3  9951       1.376963
         9955      50.620248
         9958       2.555440
         9960       8.651311
         9962       6.943470
Length: 85921, dtype: float64

In [42]:
import pandas as pd

def get_feature_data(feature_name):
    """
    Helper function to get data for a single feature and return it as a DataFrame.
    """
    df = data.get(f'fundamental_features:{feature_name}').deadline()
    # Assuming the data has 'date' as one of the columns
    # df['date'] = pd.to_datetime(df['date'])
    # df.set_index('date', inplace=True)
    return df

def combine_feature_data(feature_list):
    """
    Main function to combine data from multiple features into a single DataFrame.
    """
    # List to hold dataframes
    dfs = []
    request_times = 0
    # Loop through each feature, get the data and append to the list
    for feature in feature_list:
        if request_times == 5:
            time.sleep(5)
        df = get_feature_data(feature)
        # Rename the column to match the feature for clarity in the combined DataFrame
        df.dropna(inplace=True, axis=1, how='all')
        dfs.append(df)

        # stack_df = df.stack(dropna=False)
        # dfs.append(stack_df)
        

        #cannot request the data too often
        time.sleep(1)
        request_times+=1

    
    # Combine all the dataframes on the index (date)
    combined_df = pd.concat(dfs, axis=1, keys=feature_list)
    return combined_df.stack(dropna=False)

# List of all the features to retrieve and combine
feature_list = ['EBITDA', '營運現金流', '歸屬母公司淨利', '折舊', '流動資產', '流動負債', '取得不動產廠房及設備',
    '經常稅後淨利', 'ROA稅後息前', 'ROA綜合損益', 'ROE稅後', 'ROE綜合損益', '稅前息前折舊前淨利率', '營業毛利率',
    '營業利益率', '稅前淨利率', '稅後淨利率', '業外收支營收率', '貝里比率', '營業費用率', '推銷費用率', '管理費用率',
    '研究發展費用率', '現金流量比率', '稅率', '每股營業額', '每股營業利益', '每股現金流量', '每股稅前淨利', '每股綜合損益',
    '每股稅後淨利', '總負債除總淨值', '負債比率', '淨值除資產', '營收成長率', '營業毛利成長率', '營業利益成長率', '稅前淨利成長率',
    '稅後淨利成長率', '資產總額成長率', '淨值成長率', '流動比率', '速動比率', '利息支出率', '營運資金', '總資產週轉次數', '應收帳款週轉率'
]

# Placeholder for the actual data source
data_source = {}  # This would be the actual data source in practice

# Call the function to combine the data
combined_feature_df = combine_feature_data(feature_list)

# Assuming you would like to see the combined dataframe
combined_feature_df  # Display the combined dataframe

                     EBITDA     營運現金流  歸屬母公司淨利       折舊      流動資產       流動負債
           symbol
2013-04-30 000116       NaN       NaN      NaN      NaN       NaN        NaN  \
           000538       NaN       NaN      NaN      NaN       NaN        NaN
           000616       NaN       NaN      NaN      NaN       NaN        NaN
           000700       NaN       NaN      NaN      NaN       NaN        NaN
           000779       NaN       NaN      NaN      NaN       NaN        NaN
...                     ...       ...      ...      ...       ...        ...
2020-11-16 9982    126291.0   20640.0  48032.0  58217.0  256398.0   140790.0
           9983     25075.0    1030.0 -36157.0  60636.0  184236.0   349217.0
           9984     73877.0   82812.0   1685.0  53944.0  134566.0   579164.0
           9985     64463.0   54426.0  31603.0  24666.0  657744.0   158057.0
           9986    112558.0  181657.0  35225.0  51841.0   93944.0  1174716.0

                   取得不動產廠房及設備   經常稅後淨利   ROA稅後息前   ROA綜合損益  ...     稅前淨利成長率
           symbol                                           ...
2013-04-30 000116         NaN      NaN       NaN       NaN  ...         NaN  \
           000538         NaN      NaN       NaN       NaN  ...         NaN
           000616         NaN      NaN       NaN       NaN  ...         NaN
           000700         NaN      NaN       NaN       NaN  ...         NaN
           000779         NaN      NaN       NaN       NaN  ...         NaN
...                       ...      ...       ...       ...  ...         ...
2020-11-16 9982      -38010.0  44510.0  1.185914  0.953728  ...  -26.967994
           9983      -42329.0 -36157.0 -5.797546 -5.813237  ... -143.176571
           9984      -46514.0   1685.0  0.316756  0.067986  ...  -39.955297
           9985      -31461.0  31603.0  3.434682  3.429733  ...    1.798737
           9986      -43801.0  35225.0  1.557467  1.165481  ...    4.772781

                      稅後淨利成長率    資產總額成長率      淨值成長率        流動比率        速動比率
           symbol
2013-04-30 000116         NaN        NaN        NaN         NaN         NaN  \
           000538         NaN        NaN        NaN         NaN         NaN
           000616         NaN        NaN        NaN         NaN         NaN
           000700         NaN        NaN        NaN         NaN         NaN
           000779         NaN        NaN        NaN         NaN         NaN
...                       ...        ...        ...         ...         ...
2020-11-16 9982    -26.004123  -5.522319  -2.338719  182.113786   71.379359
           9983   -143.229316 -13.763423 -31.867371   52.756882   52.669830
           9984    -90.699856  -1.599815   0.074812   23.234524   12.751138
           9985      2.275081   1.930552   1.021651  416.143543  315.498839
           9986     52.153255   0.273247   6.629082    7.997167    6.429639

                       利息支出率       營運資金   總資產週轉次數  應收帳款週轉率
           symbol
2013-04-30 000116        NaN        NaN       NaN      NaN
           000538        NaN        NaN       NaN      NaN
           000616        NaN        NaN       NaN      NaN
           000700        NaN        NaN       NaN      NaN
           000779        NaN        NaN       NaN      NaN
...                      ...        ...       ...      ...
2020-11-16 9982    24.473313   115608.0  0.072251      NaN
           9983    -0.338331  -164981.0  0.630273      NaN
           9984    98.170840  -444598.0  0.092747      NaN
           9985     0.180103   499687.0  0.257410      NaN
           9986    31.460182 -1080772.0  0.100532      NaN

[132220 rows x 47 columns]

In [43]:
cleaned_combined_feature_df= combined_feature_df.dropna(axis=0, how='all')
date_index = cleaned_combined_feature_df.index.get_level_values(0).drop_duplicates()
date_index
stock_index = cleaned_combined_feature_df.index.get_level_values(1).drop_duplicates()
stock_index

Index(['2801', '2809', '2812', '2816', '2820', '2832', '2834', '2836', '2838',
       '2845',
       ...
       '6748', '6749', '6753', '6775', '6778', '6779', '7561', '7566', '6029',
       '6782'],
      dtype='object', name='symbol', length=2404)

In [46]:
import pandas as pd


def calculate_returns(df, date_index):
    # Convert the first level of the multi-index to a list
    # first_level_values = df.index.get_level_values(0).unique()
    first_level_values_list = date_index.tolist()

    # Sort the list of dates (if they are not in chronological order)
    first_level_values_list.sort()

    # Initialize a DataFrame to store returns
    quarterly_returns = pd.DataFrame(index=first_level_values_list, columns=df.columns)

    # Calculate returns for each 'quarter' in the first_level_values_list
    for i in range(len(first_level_values_list) - 1):
        start = first_level_values_list[i]
        end = first_level_values_list[i + 1]

        # Get start and end prices for the 'quarter'
        start_prices = df.loc[df.index.asof(start)]
        end_prices = df.loc[df.index.asof(end)]

        # Calculate returns
        returns = (end_prices - start_prices) / start_prices * 100
        
        # Assign returns to the DataFrame
        quarterly_returns.loc[end] = returns

    return quarterly_returns

# Load your DataFrame here
# df = pd.read_csv('your_data.csv')
# Assuming 'date' is part of the multi-index and each stock is a column
# df.index = pd.to_datetime(df.index)  # Convert the date index to datetime if necessary

# Call the function with your DataFrame
# returns_df = calculate_returns(df)
# Process or analyze the returns DataFrame as needed
y = calculate_returns(price_data, date_index.drop_duplicates())
y = y.stack()
y.name = 'return'

In [53]:
dataset = pd.concat([cleaned_combined_feature_df,y],axis=1).dropna(axis=0, how='all')
print(dataset.isnull().sum())
print(dataset.dropna().isnull().sum())
dataset.info()

EBITDA         6806
營運現金流          6806
歸屬母公司淨利        8818
折舊             6824
流動資產           9253
流動負債           9405
取得不動產廠房及設備     7372
經常稅後淨利         9235
ROA稅後息前       13734
ROA綜合損益        9235
ROE稅後          9129
ROE綜合損益        9354
稅前息前折舊前淨利率     8918
營業毛利率          9942
營業利益率         10236
稅前淨利率          8930
稅後淨利率          9389
業外收支營收率       11849
貝里比率           9701
營業費用率         29732
推銷費用率         29750
管理費用率         14818
研究發展費用率       24287
現金流量比率         9405
稅率             8386
每股營業額          8918
每股營業利益        10046
每股現金流量         6806
每股稅前淨利         6806
每股綜合損益         9235
每股稅後淨利         9235
總負債除總淨值        6922
負債比率           6806
淨值除資產          6922
營收成長率         26180
營業毛利成長率       26856
營業利益成長率       27336
稅前淨利成長率       23984
稅後淨利成長率       26528
資產總額成長率       23984
淨值成長率         24045
流動比率           9405
速動比率           9405
利息支出率         13529
營運資金           9253
總資產週轉次數        8918
應收帳款週轉率       18861
return        13292
dtype: int64
EBITDA        0
營運現金流         0
歸屬母公司淨利       0
折舊            0
流動資產          0
流動負債          0
取得不動產廠房及設備    0
經常稅後淨利        0
ROA稅後息前       0
ROA綜合損益       0
ROE稅後         0
ROE綜合損益       0
稅前息前折舊前淨利率    0
營業毛利率         0
營業利益率         0
稅前淨利率         0
稅後淨利率         0
業外收支營收率       0
貝里比率          0
營業費用率         0
推銷費用率         0
管理費用率         0
研究發展費用率       0
現金流量比率        0
稅率            0
每股營業額         0
每股營業利益        0
每股現金流量        0
每股稅前淨利        0
每股綜合損益        0
每股稅後淨利        0
總負債除總淨值       0
負債比率          0
淨值除資產         0
營收成長率         0
營業毛利成長率       0
營業利益成長率       0
稅前淨利成長率       0
稅後淨利成長率       0
資產總額成長率       0
淨值成長率         0
流動比率          0
速動比率          0
利息支出率         0
營運資金          0
總資產週轉次數       0
應收帳款週轉率       0
return        0
dtype: int64
<class 'finlab.dataframe.FinlabDataFrame'>
MultiIndex: 103614 entries, (Timestamp('2013-04-30 00:00:00'), '2801') to (Timestamp('2020-11-16 00:00:00'), '9188')
Data columns (total 48 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EBITDA      96808 non-null  float64
 1   營運現金流       96808 non-null  float64
 2   歸屬母公司淨利     94796 non-null  float64
 3   折舊          96790 non-null  float64
 4   流動資產        94361 non-null  float64
 5   流動負債        94209 non-null  float64
 6   取得不動產廠房及設備  96242 non-null  float64
 7   經常稅後淨利      94379 non-null  float64
 8   ROA稅後息前     89880 non-null  float64
 9   ROA綜合損益     94379 non-null  float64
 10  ROE稅後       94485 non-null  float64
 11  ROE綜合損益     94260 non-null  float64
 12  稅前息前折舊前淨利率  94696 non-null  float64
 13  營業毛利率       93672 non-null  float64
 14  營業利益率       93378 non-null  float64
 15  稅前淨利率       94684 non-null  float64
 16  稅後淨利率       94225 non-null  float64
 17  業外收支營收率     91765 non-null  float64
 18  貝里比率        93913 non-null  float64
 19  營業費用率       73882 non-null  float64
 20  推銷費用率       73864 non-null  float64
 21  管理費用率       88796 non-null  float64
 22  研究發展費用率     79327 non-null  float64
 23  現金流量比率      94209 non-null  float64
 24  稅率          95228 non-null  float64
 25  每股營業額       94696 non-null  float64
 26  每股營業利益      93568 non-null  float64
 27  每股現金流量      96808 non-null  float64
 28  每股稅前淨利      96808 non-null  float64
 29  每股綜合損益      94379 non-null  float64
 30  每股稅後淨利      94379 non-null  float64
 31  總負債除總淨值     96692 non-null  float64
 32  負債比率        96808 non-null  float64
 33  淨值除資產       96692 non-null  float64
 34  營收成長率       77434 non-null  float64
 35  營業毛利成長率     76758 non-null  float64
 36  營業利益成長率     76278 non-null  float64
 37  稅前淨利成長率     79630 non-null  float64
 38  稅後淨利成長率     77086 non-null  float64
 39  資產總額成長率     79630 non-null  float64
 40  淨值成長率       79569 non-null  float64
 41  流動比率        94209 non-null  float64
 42  速動比率        94209 non-null  float64
 43  利息支出率       90085 non-null  float64
 44  營運資金        94361 non-null  float64
 45  總資產週轉次數     94696 non-null  float64
 46  應收帳款週轉率     84753 non-null  float64
 47  return      90322 non-null  object
dtypes: float64(47), object(1)
memory usage: 38.3+ MB

In [99]:
price_data = data.get('etl:adj_close')

Daily usage: 121.3 / 500 MB - etl:adj_close

In [103]:
price_data_stock_columns = price_data.columns.to_list()

In [71]:
price_data.loc[price_data.index.asof('2013-01-02')]
# Get start and end prices for the 'quarter'
start_prices = price_data.loc[price_data.index.asof('2013-01-02')]
end_prices = price_data.loc[price_data.index.asof('2013-01-03')]

# Calculate returns
returns = (end_prices - start_prices) / start_prices * 100
quarterly_returns = pd.DataFrame(index=date_index, columns=price_data.columns)
date_index.drop_duplicates()

DatetimeIndex(['2013-04-30', '2013-05-15', '2013-08-14', '2013-09-02',
               '2013-10-31', '2013-11-14', '2014-03-31', '2014-04-30',
               '2014-05-15', '2014-08-14', '2014-09-01', '2014-10-31',
               '2014-11-14', '2015-03-31', '2015-04-30', '2015-05-15',
               '2015-08-14', '2015-08-31', '2015-11-02', '2015-11-16',
               '2016-03-31', '2016-05-03', '2016-05-16', '2016-08-15',
               '2016-08-31', '2016-10-31', '2016-11-14', '2017-03-31',
               '2017-05-02', '2017-05-15', '2017-08-14', '2017-08-31',
               '2017-10-31', '2017-11-14', '2018-04-02', '2018-04-30',
               '2018-05-15', '2018-08-14', '2018-08-31', '2018-10-31',
               '2018-11-14', '2019-04-01', '2019-04-30', '2019-05-15',
               '2019-08-14', '2019-09-02', '2019-10-31', '2019-11-14',
               '2020-03-31', '2020-04-30', '2020-05-15', '2020-08-14',
               '2020-08-31', '2020-11-02', '2020-11-16'],
              dtype='datetime64[ns]', freq=None)

In [29]:
X = cleaned_combined_feature_df.values()

In [ ]:
price_data